# Generated by Django 6.0.3 on 2026-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='verification_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_id_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
